/* Add future completed projects as entries in this collection. */
window.VIVAN_PROJECTS = [
  {
    slug: 'emami-city-e21',
    name: 'The Quiet Edit',
    siteName: 'Emami City · E1-804',
    type: 'Residential Interior',
    location: 'Kolkata',
    status: 'Completed',
    cover: './emami-city-e21/images/e21-21.webp',
    coverAlt: 'Warm contemporary living and dining room at Emami City E1-804',
    directoryDescription: 'A layered family home shaped around warm materials, thoughtful planning and the small rituals of everyday life.',
    projectDescription: 'This residence was designed with a focus on contemporary simplicity, practical planning and a warm, refined material palette. The design brings together clean architectural lines, carefully planned furniture and layered lighting to create a home that feels modern without losing its sense of comfort.',
    approach: 'The planning begins with clear movement through the home, keeping shared spaces open and restful rooms private. Furniture follows the way the family gathers and moves; considered storage keeps daily essentials close without adding visual noise. Natural stone, warm wood, tactile upholstery and measured accents create continuity from room to room. Layered ambient and task lighting brings each surface into focus, while the final choices stay grounded in the client’s routines and practical needs.',
    closing: 'The finished residence brings together the client’s requirements with our approach to planning, materials and execution—creating a space that is contemporary, comfortable and distinctly personal.',
    details: [
      { file: 'e21-13.webp', alt: 'Close view of the dark stone vanity and carefully finished surfaces' },
      { file: 'e21-11.webp', alt: 'Kitchen worktop and cabinetry, composed around everyday use' },
      { file: 'e21-14.webp', alt: 'Vanity, mirror and lighting details in the bathroom' }
    ],
    gallery: [
      { file: 'e21-01.webp', alt: 'Wide view of the layered master bedroom with warm neutral finishes', width: 2400, height: 1600 },
      { file: 'e21-02.webp', alt: 'Bedroom with upholstered headboard and softly layered lighting', width: 2400, height: 1600 },
      { file: 'e21-03.webp', alt: 'Bedroom view showing custom storage and considered furniture placement', width: 2400, height: 1600 },
      { file: 'e21-04.webp', alt: 'Bright bedroom with a green stone feature wall', width: 2400, height: 1592 },
      { file: 'e21-05.webp', alt: 'Bedroom with patterned textiles and warm bedside lighting', width: 2400, height: 1600 },
      { file: 'e21-06.webp', alt: 'Bedroom interior with a sculptural mirror and restrained palette', width: 2400, height: 1600 },
      { file: 'e21-07.webp', alt: 'Calm bedroom with full-height wardrobe detailing', width: 2400, height: 1600 },
      { file: 'e21-08.webp', alt: 'Bedroom framed by clean architectural lines and a green stone wall', width: 2400, height: 1600 },
      { file: 'e21-09.webp', alt: 'Bedroom with an upholstered bed and soft indirect light', width: 2400, height: 1600 },
      { file: 'e21-10.webp', alt: 'Modern kitchen and island with integrated storage', width: 2400, height: 1600 },
      { file: 'e21-11.webp', alt: 'Portrait detail of the kitchen worktop and cabinetry', width: 1600, height: 2400 },
      { file: 'e21-12.webp', alt: 'Kitchen sink and counter with carefully selected finishes', width: 1600, height: 2400 },
      { file: 'e21-13.webp', alt: 'Dark stone vanity and bathroom material detail', width: 1600, height: 2400 },
      { file: 'e21-14.webp', alt: 'Vanity details with reflective surfaces and layered light', width: 1769, height: 2400 },
      { file: 'e21-15.webp', alt: 'Dining and lounge area arranged for relaxed conversation', width: 2400, height: 1600 },
      { file: 'e21-16.webp', alt: 'Open-plan kitchen, dining and living spaces', width: 2400, height: 1600 },
      { file: 'e21-17.webp', alt: 'Dining area with warm timber and sculptural lighting', width: 2400, height: 1571 },
      { file: 'e21-18.webp', alt: 'Portrait view of a softly styled living room corner', width: 1600, height: 2400 },
      { file: 'e21-19.webp', alt: 'Living room seating with a warm, contemporary palette', width: 1689, height: 2400 },
      { file: 'e21-20.webp', alt: 'Living and dining area with tactile materials and soft curves', width: 2400, height: 1633 },
      { file: 'e21-21.webp', alt: 'Wide interior view of the living and dining room', width: 2400, height: 1600 },
      { file: 'e21-22.webp', alt: 'Living room with layered upholstery and warm light', width: 2400, height: 1551 },
      { file: 'e21-23.webp', alt: 'Contemporary living room with thoughtful lighting and material contrast', width: 2400, height: 1600 },
      { file: 'e21-24.webp', alt: 'Portrait view of a calm seating corner and curved detailing', width: 1600, height: 2400 }
    ]
  },
  {
    slug: 'c2-1201',
    name: 'C2 1201',
    siteName: 'Emami City · C2-1201',
    type: 'Residential Interior',
    location: 'Kolkata',
    status: 'Completed',
    cover: './c2-1201/images/c2-1201-18.webp',
    hero: 'c2-1201-19.webp',
    coverAlt: 'Living and dining space at the C2 1201 residence',
    directoryDescription: 'A layered Emami City home where calm bedrooms meet expressive accents and an inviting shared living space.',
    projectDescription: 'This Emami City residence brings together restful bedrooms, clean-lined kitchen cabinetry and an expressive shared living area. A considered mix of warm neutrals and vivid accents gives the home its own character while keeping everyday living at the centre.',
    approach: 'The interiors move from quieter private rooms into a generous living and dining space. Clear lines, considered storage and layered lighting bring continuity through the home, while selected colour and pattern create distinct moments. The gallery follows that journey from the bedrooms and kitchen to the details and shared spaces.',
    closing: 'C2 1201 brings a composed private palette together with lively shared rooms—an individual home shaped through its details, colour and everyday flow.',
    details: [
      { file: 'c2-1201-11.webp', alt: 'Kitchen counter and cabinetry detail' },
      { file: 'c2-1201-15.webp', alt: 'Bathroom vanity and reflective finish detail' },
      { file: 'c2-1201-24.webp', alt: 'Blue entry door and adjoining wall finish' }
    ],
    gallery: [
      { file: 'c2-1201-01.webp', alt: 'Wide view of a calm bedroom with layered neutral finishes', width: 2400, height: 1568 },
      { file: 'c2-1201-02.webp', alt: 'Bedroom with a warm upholstered headboard and soft lighting', width: 2400, height: 1561 },
      { file: 'c2-1201-03.webp', alt: 'Bedroom viewed from the foot of the bed', width: 2400, height: 1682 },
      { file: 'c2-1201-04.webp', alt: 'Portrait view of the bedroom and window-side detailing', width: 1636, height: 2400 },
      { file: 'c2-1201-05.webp', alt: 'Bedroom with a considered palette and custom furnishings', width: 2400, height: 1600 },
      { file: 'c2-1201-06.webp', alt: 'Vertical bedroom view with full-height storage and soft finishes', width: 1669, height: 2400 },
      { file: 'c2-1201-07.webp', alt: 'Bedroom interior with a framed bed and warm accents', width: 2400, height: 1600 },
      { file: 'c2-1201-08.webp', alt: 'A further view across the bedroom interior', width: 2400, height: 1600 },
      { file: 'c2-1201-09.webp', alt: 'Bright kitchen with a long counter and integrated cabinetry', width: 2400, height: 1603 },
      { file: 'c2-1201-10.webp', alt: 'Kitchen work area and cabinetry from a second angle', width: 2400, height: 1600 },
      { file: 'c2-1201-11.webp', alt: 'Portrait detail of the kitchen counter and finishes', width: 1600, height: 2400 },
      { file: 'c2-1201-12.webp', alt: 'Bathroom interior with carefully coordinated surfaces', width: 2400, height: 1600 },
      { file: 'c2-1201-13.webp', alt: 'Portrait view of a bathroom and vanity area', width: 1604, height: 2400 },
      { file: 'c2-1201-14.webp', alt: 'Bathroom storage and finish details', width: 1600, height: 2400 },
      { file: 'c2-1201-15.webp', alt: 'Close view of the bathroom vanity and mirror', width: 1600, height: 2400 },
      { file: 'c2-1201-16.webp', alt: 'A dedicated prayer space with detailed wall and cabinet finishes', width: 1600, height: 2400 },
      { file: 'c2-1201-17.webp', alt: 'Living room and dining area seen through the interior', width: 1763, height: 2400 },
      { file: 'c2-1201-18.webp', alt: 'Wide living and dining room with warm timber details', width: 2400, height: 1600 },
      { file: 'c2-1201-19.webp', alt: 'Open view across the finished living and dining space', width: 2400, height: 1565 },
      { file: 'c2-1201-20.webp', alt: 'Portrait detail of the living room seating and finishes', width: 1644, height: 2400 },
      { file: 'c2-1201-21.webp', alt: 'Dining area with sculptural lighting and a composed table setting', width: 2400, height: 1600 },
      { file: 'c2-1201-22.webp', alt: 'Dining room viewed from the opposite side', width: 2400, height: 1600 },
      { file: 'c2-1201-23.webp', alt: 'Close view of furniture and material details in the shared space', width: 2400, height: 1600 },
      { file: 'c2-1201-24.webp', alt: 'Portrait view of a vivid blue entrance door and surrounding finish', width: 1600, height: 2400 }
    ]
  },
  {
    slug: 'c2-1204',
    name: 'C2 1204',
    siteName: 'Emami City · C2-1204',
    type: 'Residential Interior',
    location: 'Kolkata',
    status: 'Completed',
    cover: './c2-1204/images/c2-1204-17.webp',
    hero: 'c2-1204-18.webp',
    balancedGallery: true,
    coverAlt: 'Living room at the C2 1204 residence',
    directoryDescription: 'A light-filled Emami City residence with soft neutrals, warm timber and gently expressive details.',
    projectDescription: 'C2 1204 pairs soft neutral rooms with warm timber, reflective surfaces and considered accents of colour. The living and dining spaces open into one another, while bedrooms and quieter corners bring a more intimate pace to the home.',
    approach: 'The gallery moves from the bedrooms into the kitchen and bathroom finishes before opening into the shared living and dining rooms. Soft surfaces and warm wood tones give the spaces continuity; lighting and selected details bring definition without crowding the composition.',
    closing: 'The completed home balances open shared rooms with quieter private spaces, giving C2 1204 a calm, personal character throughout.',
    details: [
      { file: 'c2-1204-08.webp', alt: 'Dark marble basin and veined stone bathroom finish' },
      { file: 'c2-1204-09.webp', alt: 'Warm backlit kitchen stone and counter detail' },
      { file: 'c2-1204-11.webp', alt: 'Sculptural basin against a richly veined stone vanity wall' }
    ],
    gallery: [
      { file: 'c2-1204-01.webp', alt: 'Bedroom with a softly patterned headboard wall and warm light', width: 2400, height: 1600 },
      { file: 'c2-1204-02.webp', alt: 'Portrait view of a calm bedroom and window-side furnishings', width: 1612, height: 2400 },
      { file: 'c2-1204-03.webp', alt: 'Bedroom with layered blush and neutral tones', width: 1600, height: 2400 },
      { file: 'c2-1204-04.webp', alt: 'Portrait view across the bedroom and its soft finishes', width: 1648, height: 2400 },
      { file: 'c2-1204-05.webp', alt: 'A further bedroom view with warm timber detailing', width: 1600, height: 2400 },
      { file: 'c2-1204-06.webp', alt: 'Bedroom with window light and understated furnishings', width: 2400, height: 1600 },
      { file: 'c2-1204-07.webp', alt: 'Bedroom storage and bedside details', width: 2400, height: 1600 },
      { file: 'c2-1204-08.webp', alt: 'Portrait detail of a dark marble basin and veined stone bathroom finish', width: 1600, height: 2400 },
      { file: 'c2-1204-09.webp', alt: 'Portrait view of the kitchen’s warm backlit stone and counter detail', width: 1632, height: 2400 },
      { file: 'c2-1204-10.webp', alt: 'Kitchen with integrated storage and warm counter lighting', width: 2400, height: 1578 },
      { file: 'c2-1204-11.webp', alt: 'Portrait view of the bathroom vanity and stone surface', width: 1600, height: 2400 },
      { file: 'c2-1204-12.webp', alt: 'Bathroom mirror, basin and material detail', width: 1600, height: 2400 },
      { file: 'c2-1204-13.webp', alt: 'Living space with sculptural furniture and natural light', width: 2400, height: 1600 },
      { file: 'c2-1204-14.webp', alt: 'Wide view of the connected living and dining area', width: 2400, height: 1600 },
      { file: 'c2-1204-15.webp', alt: 'Portrait view of a living room corner and soft furnishings', width: 1674, height: 2400 },
      { file: 'c2-1204-16.webp', alt: 'Living room with layered seating and warm finishes', width: 2400, height: 1549 },
      { file: 'c2-1204-17.webp', alt: 'Living room composed around natural light and custom furniture', width: 2400, height: 1600 },
      { file: 'c2-1204-18.webp', alt: 'Open view across the living and dining rooms', width: 2400, height: 1600 },
      { file: 'c2-1204-19.webp', alt: 'Portrait view of the dining area and its lighting', width: 1735, height: 2400 },
      { file: 'c2-1204-20.webp', alt: 'Dining area with warm accents and considered furnishings', width: 2400, height: 1600 },
      { file: 'c2-1204-21.webp', alt: 'Living and dining space seen from the adjoining room', width: 2400, height: 1600 },
      { file: 'c2-1204-22.webp', alt: 'Another wide view through the shared living area', width: 2400, height: 1600 },
      { file: 'c2-1204-23.webp', alt: 'Portrait view of a quiet corner and timber detailing', width: 1735, height: 2400 },
      { file: 'c2-1204-24.webp', alt: 'Wide view through the connected rooms of the residence', width: 2400, height: 1600 }
    ]
  },
  {
    slug: 'a2-1203',
    name: 'A2 1203',
    siteName: 'Emami City · A2-1203',
    type: 'Residential Interior',
    location: 'Kolkata',
    status: 'Completed',
    cover: './a2-1203/images/a2-1203-22.webp',
    hero: 'a2-1203-20.webp',
    balancedGallery: true,
    coverAlt: 'Living room at the A2 1203 residence',
    directoryDescription: 'A quiet Emami City home shaped by considered neutrals, soft textures and expressive green accents.',
    projectDescription: 'A2 1203 brings together a softly layered bedroom, a second room for work and rest, a considered kitchen, and an open living and dining space. Gentle greens, warm neutrals and tactile finishes give each room its own character while keeping the home visually connected.',
    approach: 'The project moves through a series of distinct moods: a bedroom framed by green botanical detailing, a flexible secondary room, clean-lined kitchen and bath spaces, then a light-filled living room. The gallery follows that sequence, bringing the details and wider views together as one home.',
    closing: 'The finished residence brings a calm, natural palette through the rooms, with distinct spaces for rest, work and time together.',
    details: [
      { file: 'a2-1203-11.webp', alt: 'Portrait detail of the kitchen counter and cabinetry' },
      { file: 'a2-1203-14.webp', alt: 'Bathroom basin framed by warm stone and a round mirror' },
      { file: 'a2-1203-03.webp', alt: 'Bedroom detail with a soft headboard and leafy green accent' }
    ],
    gallery: [
      { file: 'a2-1203-01.webp', alt: 'Bedroom with a leafy green accent and warm neutral bedding', width: 2400, height: 1600 },
      { file: 'a2-1203-02.webp', alt: 'Bedroom framed by a soft green patterned feature wall', width: 2400, height: 1631 },
      { file: 'a2-1203-03.webp', alt: 'Close view of the bedroom headboard, bedding and green detail', width: 1600, height: 2400 },
      { file: 'a2-1203-04.webp', alt: 'Portrait view of the bedroom and its window-side details', width: 1600, height: 2400 },
      { file: 'a2-1203-05.webp', alt: 'Wide bedroom view with soft textures and considered lighting', width: 2400, height: 1600 },
      { file: 'a2-1203-06.webp', alt: 'A second view across the bedroom and storage wall', width: 2400, height: 1600 },
      { file: 'a2-1203-07.webp', alt: 'A study and secondary room with a desk and window-side bed', width: 2400, height: 1608 },
      { file: 'a2-1203-08.webp', alt: 'Study space with a desk, chair and tailored wall finish', width: 2400, height: 1600 },
      { file: 'a2-1203-09.webp', alt: 'Secondary bedroom with a desk and subtle wall pattern', width: 2400, height: 1600 },
      { file: 'a2-1203-10.webp', alt: 'Modern kitchen with clean-lined cabinetry and counter lighting', width: 2400, height: 1600 },
      { file: 'a2-1203-11.webp', alt: 'Portrait view of the kitchen worktop, backsplash and cabinetry', width: 1600, height: 2400 },
      { file: 'a2-1203-12.webp', alt: 'Kitchen counter and cabinetry seen from another angle', width: 2400, height: 1600 },
      { file: 'a2-1203-13.webp', alt: 'Portrait view of a bathroom with warm stone finishes', width: 1600, height: 2400 },
      { file: 'a2-1203-14.webp', alt: 'Bathroom basin and round mirror set against textured stone', width: 1681, height: 2400 },
      { file: 'a2-1203-15.webp', alt: 'Close perspective across the bathroom basin and counter', width: 1600, height: 2400 },
      { file: 'a2-1203-16.webp', alt: 'Portrait view of the bathroom fittings and wall finish', width: 1600, height: 2400 },
      { file: 'a2-1203-17.webp', alt: 'Bedroom with a warm patterned feature wall and soft furnishings', width: 2400, height: 1600 },
      { file: 'a2-1203-18.webp', alt: 'Bed, wardrobe and window arranged in a quiet neutral palette', width: 2400, height: 1600 },
      { file: 'a2-1203-19.webp', alt: 'Bedroom view with full-height wardrobe detailing', width: 2400, height: 1600 },
      { file: 'a2-1203-20.webp', alt: 'Light-filled living room with a generous seating arrangement', width: 2400, height: 1600 },
      { file: 'a2-1203-21.webp', alt: 'Portrait view of the living and dining area', width: 1766, height: 2400 },
      { file: 'a2-1203-22.webp', alt: 'Living room with warm upholstery and a sculptural television wall', width: 2400, height: 1600 },
      { file: 'a2-1203-23.webp', alt: 'Living area with a considered mix of light and warm finishes', width: 2400, height: 1608 },
      { file: 'a2-1203-24.webp', alt: 'Portrait view of the dining area and adjoining living space', width: 1625, height: 2400 }
    ]
  }
];
